import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
const main = await readFile('src/main.js','utf8');
const data = await readFile('src/data.js','utf8');
const index = await readFile('index.html','utf8');
const manifest = await readFile('public/manifest.webmanifest','utf8');
const routes = ['/', '/engine/', '/profile/', '/works/'];
assert.match(main, /localStorage\.getItem\('wwhooo-lang'\)/);
assert.match(main, /setItem\('wwhooo-lang'/);
assert.match(main, /path=='\/engine'/);
assert.match(main, /path=='\/profile'/);
assert.match(main, /path=='\/works'/);
assert.match(main, /p\[5\]/, 'project links must use the URL field');
assert.doesNotMatch(main, /href="\$\{p\[4\]\}"/, 'English description must not be used as URL');
assert.match(main, /rel="noopener noreferrer"/);
assert.match(data, /sakura\.jpg/);
assert.match(index, /src="\/src\/main\.js"/);
assert.equal(JSON.parse(manifest).start_url, '/');
await access('public/images/photography/sakura.jpg', constants.R_OK);
for (const route of routes) assert.ok(route.startsWith('/'), `route ${route}`);
console.log(`site checks passed: ${routes.length} routes, bilingual switch, project links, photography asset`);
