// Client-side router: route table, per-route document head, and link handling.
//
// Every route also exists as a real static file (generated by
// scripts/build-routes.mjs), so a direct hit is served by Nginx with the correct
// <title>/canonical and never needs a GitHub Pages style 404 redirect. This
// module only handles in-page navigations after the first paint.

import { subsites } from './data.js';
import { getLang } from './i18n.js';
import { FALLBACK_META, ROUTE_META, SITE_URL } from './meta.js';
import { hasEntered } from './session.js';
import { engine, home, notFound, profilePage, subsite, works } from './views.js';

const ROUTES = {
  '/': home,
  '/engine/': engine,
  '/profile/': profilePage,
  '/works/': works,
  '/toy/': () => subsite(subsites[0]),
  '/notes/': () => subsite(subsites[1]),
};

export { ROUTE_PATHS as routePaths } from './meta.js';

/** Normalise `location.pathname` (or any href) to a key in ROUTES. */
export function normalize(pathname) {
  const trimmed = pathname.replace(/\/+$/, '');
  if (trimmed === '' || trimmed === '/index.html') return '/';
  return `${trimmed}/`;
}

export const currentPath = () => normalize(location.pathname);

// ---------------------------------------------------------------- head sync

function upsertMeta(attr, key, content) {
  let el = document.head.querySelector(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute(attr, key);
    document.head.append(el);
  }
  el.setAttribute('content', content);
}

function upsertLink(rel, href) {
  let el = document.head.querySelector(`link[rel="${rel}"]`);
  if (!el) {
    el = document.createElement('link');
    el.setAttribute('rel', rel);
    document.head.append(el);
  }
  el.setAttribute('href', href);
}

export function applyHead(path, meta) {
  const lang = getLang();
  const title = meta.title[lang];
  const description = meta.description[lang];
  const canonical = path ? `${SITE_URL}${path}` : `${SITE_URL}/`;

  document.title = title;
  upsertMeta('name', 'description', description);
  upsertMeta('property', 'og:title', title);
  upsertMeta('property', 'og:description', description);
  upsertMeta('property', 'og:url', canonical);
  upsertMeta('name', 'robots', meta.noindex ? 'noindex, follow' : 'index, follow');
  upsertLink('canonical', canonical);
}

// ------------------------------------------------------------------- mount

const app = () => document.querySelector('#app');

let afterRender = () => {};

/** Register work that must run after every render (interaction wiring). */
export const onAfterRender = (fn) => {
  afterRender = fn;
};

/** Render `path` into #app and sync the document head. Returns whether it matched a route. */
export function mount(path = currentPath()) {
  const known = Object.hasOwn(ROUTES, path);
  const render = known ? ROUTES[path] : notFound;
  app().innerHTML = render();
  applyHead(known ? path : null, known ? ROUTE_META[path] : FALLBACK_META);
  document.body.classList.toggle('is-locked', path === '/' && !hasEntered());
  afterRender();
  return known;
}

/** Navigate without a full page load. */
export function navigate(path, { hash = '', replace = false } = {}) {
  const url = `${path}${hash}`;
  if (replace) history.replaceState({ path }, '', url);
  else history.pushState({ path }, '', url);
  mount(path);
  if (hash) {
    document.querySelector(hash)?.scrollIntoView();
    return;
  }
  window.scrollTo(0, 0);
  document.querySelector('#top')?.focus({ preventScroll: true });
}

/** Intercept same-origin clicks on known routes; everything else stays native. */
export function initLinks() {
  document.addEventListener('click', (event) => {
    if (event.defaultPrevented || event.button !== 0) return;
    if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    const anchor = event.target.closest?.('a');
    if (!anchor || anchor.target === '_blank' || anchor.hasAttribute('download')) return;

    const url = new URL(anchor.href, location.href);
    if (url.origin !== location.origin) return;

    const path = normalize(url.pathname);
    if (!Object.hasOwn(ROUTES, path)) return;
    if (url.pathname === location.pathname && url.hash) return; // let the browser scroll

    event.preventDefault();
    if (url.pathname === location.pathname) {
      window.scrollTo(0, 0);
      return;
    }
    navigate(path, { hash: url.hash });
  });

  window.addEventListener('popstate', () => {
    mount(currentPath());
  });
}
