// Client-side router: route resolution, per-language document head, and link
// handling.
//
// The language is part of the URL. `/engine/` is the Chinese page and
// `/en/engine/` the English one; each exists as a real static file generated by
// scripts/build-routes.mjs, carrying its own <title>, canonical and reciprocal
// hreflang alternates. This module only handles in-page navigations after the
// first paint — it never has to invent metadata that the server did not send.

import { subsites } from './data.js';
import { setContext } from './context.js';
import {
  FALLBACK_META,
  OG_LOCALE,
  SITE_URL,
  alternatesFor,
  getRouteDef,
  inferLang,
  normalizePath,
  resolveRoute,
} from './meta.js';
import { hasEntered } from './session.js';
import { engine, home, notFound, profilePage, searchPage, subsite, works } from './views.js';

const RENDERERS = {
  home,
  engine,
  profile: profilePage,
  works,
  search: searchPage,
  toy: () => subsite(subsites[0]),
  notes: () => subsite(subsites[1]),
};

export { normalizePath };

export const currentPath = () => normalizePath(location.pathname);

// ---------------------------------------------------------------- head sync

function upsertMeta(attr, key, content) {
  let el = document.head.querySelector(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute(attr, key);
    document.head.append(el);
  }
  el.setAttribute('content', content);
}

function removeMeta(attr, key) {
  document.head.querySelector(`meta[${attr}="${key}"]`)?.remove();
}

function upsertLink(rel, href) {
  let el = document.head.querySelector(`link[rel="${rel}"]:not([hreflang])`);
  if (!el) {
    el = document.createElement('link');
    el.setAttribute('rel', rel);
    document.head.append(el);
  }
  el.setAttribute('href', href);
}

function removeLink(rel) {
  document.head.querySelector(`link[rel="${rel}"]:not([hreflang])`)?.remove();
}

function upsertAlternate(hreflang, href) {
  let el = document.head.querySelector(`link[rel="alternate"][hreflang="${hreflang}"]`);
  if (!el) {
    el = document.createElement('link');
    el.setAttribute('rel', 'alternate');
    el.setAttribute('hreflang', hreflang);
    document.head.append(el);
  }
  el.setAttribute('href', href);
}

function clearAlternates() {
  document.head.querySelectorAll('link[rel="alternate"][hreflang]').forEach((el) => el.remove());
}

/**
 * @param def  route definition from ./meta.js, or null for an unknown path
 * @param lang 'zh' | 'en'
 */
export function applyHead(def, lang) {
  const meta = def ?? FALLBACK_META;

  document.title = meta.title[lang];
  upsertMeta('name', 'description', meta.description[lang]);
  upsertMeta('property', 'og:title', meta.title[lang]);
  upsertMeta('property', 'og:description', meta.description[lang]);
  upsertMeta('property', 'og:locale', OG_LOCALE[lang]);
  upsertMeta('name', 'robots', meta.noindex ? 'noindex, follow' : 'index, follow');

  if (!def) {
    // An unknown path must not claim to be the homepage: drop the canonical and
    // the alternates rather than pointing them at `/`.
    removeMeta('property', 'og:url');
    removeLink('canonical');
    clearAlternates();
    return;
  }

  const canonical = `${SITE_URL}${def.path[lang]}`;
  upsertMeta('property', 'og:url', canonical);
  upsertLink('canonical', canonical);
  for (const alt of alternatesFor(def.id)) upsertAlternate(alt.hreflang, alt.href);
}

// ------------------------------------------------------------------- mount

const app = () => document.querySelector('#app');

let afterRender = () => {};

/** Register work that must run after every render (interaction wiring). */
export const onAfterRender = (fn) => {
  afterRender = fn;
};

// The build prerenders every route, so on a fresh page load the container
// already holds exactly the markup this module would produce. Rebuilding it
// would discard painted content and force a full re-parse for no gain, so the
// very first mount reconciles instead. `data-prerendered` (written by
// scripts/build-routes.mjs, empty in the dev shell) is the guard against
// reusing the wrong page — a misconfigured server handing back the homepage
// must not silently render the homepage at an /en/works/ URL.
let reconciled = false;

/**
 * Render `path` into #app and sync the document head.
 * Returns the resolved route id, or null when the path is unknown.
 */
export function mount(path = currentPath()) {
  const resolved = resolveRoute(path);
  const lang = resolved ? resolved.lang : inferLang(path);
  const id = resolved ? resolved.id : null;
  const def = id ? getRouteDef(id) : null;
  const root = app();

  setContext(lang, id);
  const stamp = `${id ?? 'notfound'}:${lang}`;
  const reuse = !reconciled && root.dataset.prerendered === stamp;
  if (!reuse) root.innerHTML = (id ? RENDERERS[id] : notFound)();
  reconciled = true;

  applyHead(def, lang);
  document.body.classList.toggle('is-locked', id === 'home' && !hasEntered());
  // gate.js reconciles the locked/unlocked classes for the reused markup, which
  // was prerendered with hasEntered() === false.
  afterRender();
  return id;
}

function focusRouteTop() {
  window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
  document.querySelector('#top')?.focus({ preventScroll: true });
}

/** Navigate without a full page load. */
export function navigate(path, { hash = '', replace = false } = {}) {
  const url = `${path}${hash}`;
  if (replace) history.replaceState({ path }, '', url);
  else history.pushState({ path }, '', url);
  mount(path);
  if (hash) {
    document.querySelector(hash)?.scrollIntoView();
    return;
  }
  focusRouteTop();
}

/** Intercept same-origin clicks on known routes; everything else stays native. */
export function initLinks() {
  history.scrollRestoration = 'manual';
  document.addEventListener('click', (event) => {
    if (event.defaultPrevented || event.button !== 0) return;
    if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    const anchor = event.target.closest?.('a');
    if (!anchor || anchor.target === '_blank' || anchor.hasAttribute('download')) return;

    const url = new URL(anchor.getAttribute('href') ?? '', location.href);
    if (url.origin !== location.origin) return;

    const path = normalizePath(url.pathname);
    if (!resolveRoute(path)) return;
    if (url.pathname === location.pathname && url.hash) return; // let the browser scroll

    event.preventDefault();
    if (url.pathname === location.pathname) {
      window.scrollTo(0, 0);
      return;
    }
    navigate(path, { hash: url.hash });
  });

  window.addEventListener('popstate', () => {
    mount(currentPath());
    focusRouteTop();
  });
}
